
'''
Module that calculates the piecewise linear interpolation of a linear function, returning
the slope and y-intercept of the line generated by connecting two given points.
'''

def interpolate(y0: float, y1: float, x0: float, x1: float):
    """
    Calculate the slope and y-intercept between two points represented by two tuples
    of x and y values.

    Args:
        y0: the y-value of the first point

        x0: the x-value of the first point

        y1: the y-value of the second point

        x1: the x-value of the second point

    Yields:
        A tuple containing the calculated slope and y-intercept
    """

    slope = float(y1 - y0) / float(x1 - x0)
    intercept = y0 - (slope * x0)

    return (slope, intercept)